print("My name is Srivarsha")
print("My age is 8")
print("my grade is 3")
print("My school name is PSBB Millenium school")
print("My friends names are Bhavathi,Swara,Piraitendral")
print("My favourite food is curd rice with ocra curry")
print("My favourite place is school")
print("My hobby is coding")
print("My dog name is REMO,He is 1 year 3 months old")
print("My favourite subject is EVS")
print("My favourite game is imposter")
print("My favourite colour is indigo")