print("My name is Aanya")
print("My age is 8")
print("My grade is 3")
print("My school name is Sunshine School")
print("My friends names are Riya, Arjun, Kavin")
print("My favourite food is pizza")
print("My favourite place is playground")
print("My hobby is drawing")
print("My pet name is Bruno, He is 2 years old")
print("My favourite subject is Science")
print("My favourite game is hide and seek")
print("My favourite colour is blue")