# Program Code: OUT-HOT-03
# Title: Output Mini App — Personal Profile Builder
# Cognitive Skill: Higher Order Thinking (Creative Synthesis)
# Topic: Output in Python

# Build a complete profile builder — collects info and displays
# it in multiple stylish formats using everything learned about output.

print("╔══════════════════════════════════╗")
print("║   Progra Profile Builder        ║")
print("╚══════════════════════════════════╝")
print()

# --- Collect information ---
print("Let's build your profile! Answer a few questions.")
print()
name        = input("Full name: ")
age         = int(input("Age: "))
city        = input("City: ")
school      = input("School: ")
fav_subject = input("Favourite subject: ")
fav_sport   = input("Favourite sport: ")
hobby       = input("Hobby: ")
dream       = input("Dream career: ")
fav_food    = input("Favourite food: ")

print()
print("Choose your profile style:")
print("1. Simple Card")
print("2. Formal Report")
print("3. Fun Banner")

style = input("Style (1/2/3): ").strip()

# --- Style 1: Simple Card ---
if style == "1":
    w = 36
    print()
    print("+" + "=" * (w-2) + "+")
    print("|" + "MY PROFILE".center(w-2) + "|")
    print("+" + "-" * (w-2) + "+")
    for label, value in [
        ("Name",    name),
        ("Age",     age),
        ("City",    city),
        ("School",  school),
        ("Subject", fav_subject),
        ("Sport",   fav_sport),
        ("Hobby",   hobby),
        ("Dream",   dream),
        ("Food",    fav_food),
    ]:
        print("| " + str(label).ljust(10) + ": " + str(value).ljust(w-15) + "|")
    print("+" + "=" * (w-2) + "+")

# --- Style 2: Formal Report ---
elif style == "2":
    print()
    print("=" * 45)
    print("STUDENT PROFILE REPORT".center(45))
    print("=" * 45)
    print("  Name            : " + name)
    print("  Age             : " + str(age) + " years old")
    print("  City            : " + city)
    print("  School          : " + school)
    print("-" * 45)
    print("  Favourite Subject: " + fav_subject)
    print("  Favourite Sport  : " + fav_sport)
    print("  Hobby            : " + hobby)
    print("  Dream Career     : " + dream)
    print("  Favourite Food   : " + fav_food)
    print("=" * 45)
    print("  " + "Generated by Progra Profile Builder".center(43))
    print("=" * 45)

# --- Style 3: Fun Banner ---
elif style == "3":
    initials  = "".join(word[0].upper() for word in name.split())
    star_line = "*" * (len(name) + 8)
    print()
    print("  " + star_line)
    print("  ** Hi, I am " + name + "! **")
    print("  " + star_line)
    print()
    print("  [" + initials + "] = " + name.upper())
    age_icon = "🎂" if age < 18 else "👤"
    print("  Age  : " + age_icon + " " + str(age) + " years young!")
    print("  City : " + city)
    print()
    print("  I LOVE  : " + fav_subject + " | " + fav_sport + " | " + hobby)
    print("  I EAT   : " + fav_food)
    print("  I DREAM : To be a " + dream + "!")
    print()
    first_name = name.split()[0]
    print(("Go " + first_name + "! Code. Think. Lead.").center(40))
else:
    print("Invalid style. Showing simple version.")
    print("Name: " + name + " | Age: " + str(age) + " | City: " + city)

# Think:
# 1. Add a Style 4 that shows the profile as a business card.
# 2. How would you save this output to a text file instead of the screen?
