# Program Code: OUT-HOT-03
# Title: Output Mini App — Personal Profile Builder
# Cognitive Skill: Higher Order Thinking (Creative Synthesis)
# Topic: Output in Python

# Build a complete profile builder — collects info and displays
# it in multiple stylish formats using everything learned about output.

print("╔══════════════════════════════════╗")
print("║   Progra Profile Builder        ║")
print("╚══════════════════════════════════╝")
print()

# --- Collect information ---
print("Let's build your profile! Answer a few questions.")
print()
name        = input("Full name: ")
age         = int(input("Age: "))
city        = input("City: ")
school      = input("School: ")
fav_subject = input("Favourite subject: ")
fav_sport   = input("Favourite sport: ")
hobby       = input("Hobby: ")
dream       = input("Dream career: ")
fav_food    = input("Favourite food: ")

print()
print("Choose your profile style:")
print("1. Simple Card")
print("2. Formal Report")
print("3. Fun Banner")

style = input("Style (1/2/3): ").strip()

# --- Style 1: Simple Card ---
if style == "1":
    w = 36
    print()
    print("+" + "=" * (w-2) + "+")
    print(f"|{'MY PROFILE':^{w-2}}|")
    print("+" + "-" * (w-2) + "+")
    for label, value in [
        ("Name",    name),
        ("Age",     age),
        ("City",    city),
        ("School",  school),
        ("Subject", fav_subject),
        ("Sport",   fav_sport),
        ("Hobby",   hobby),
        ("Dream",   dream),
        ("Food",    fav_food),
    ]:
        print(f"| {label:<10}: {str(value):<{w-15}}|")
    print("+" + "=" * (w-2) + "+")

# --- Style 2: Formal Report ---
elif style == "2":
    print()
    print("=" * 45)
    print(f"{'STUDENT PROFILE REPORT':^45}")
    print("=" * 45)
    print(f"  Name            : {name}")
    print(f"  Age             : {age} years old")
    print(f"  City            : {city}")
    print(f"  School          : {school}")
    print("-" * 45)
    print(f"  Favourite Subject: {fav_subject}")
    print(f"  Favourite Sport  : {fav_sport}")
    print(f"  Hobby            : {hobby}")
    print(f"  Dream Career     : {dream}")
    print(f"  Favourite Food   : {fav_food}")
    print("=" * 45)
    print(f"  {'Generated by Progra Profile Builder':^43}")
    print("=" * 45)

# --- Style 3: Fun Banner ---
elif style == "3":
    initials = "".join(w[0].upper() for w in name.split())
    print()
    print(f"  {'*' * (len(name) + 8)}")
    print(f"  ** Hi, I am {name}! **")
    print(f"  {'*' * (len(name) + 8)}")
    print()
    print(f"  [{initials}] = {name.upper()}")
    print(f"  Age  : {'🎂' if age < 18 else '👤'} {age} years young!")
    print(f"  City : {city}")
    print()
    print(f"  I LOVE  : {fav_subject} | {fav_sport} | {hobby}")
    print(f"  I EAT   : {fav_food}")
    print(f"  I DREAM : To be a {dream}!")
    print()
    print(f"  {'Go ' + name.split()[0] + '! Code. Think. Lead.':^40}")
else:
    print("Invalid style. Showing simple version.")
    print(f"Name: {name} | Age: {age} | City: {city}")

# Think:
# 1. Add a Style 4 that shows the profile as a business card.
# 2. How would you save this output to a text file instead of the screen?
